### ISSUE TITLE
Is this any Vital Error or should be ignored ?

### ISSUE THREAD

**Issue by dg28gadhavi** [cyxx/extract_android_ota_payload#1]
ssh@bash:~/ext$ python extract_android_ota_payload.py up.zip out
Extracting 'payload.bin' from OTA file...
Extracting 'abl.img'
Traceback (most recent call last):
  File "extract_android_ota_payload.py", line 75, in <module>
    main(sys.argv)
  File "extract_android_ota_payload.py", line 72, in main
    parse_payload(payload, p, out_f)
  File "extract_android_ota_payload.py", line 40, in parse_payload
    raise update_payload.error.PayloadError('Unknown operation type (%d)' % operat
ion.type)
update_payload.error.PayloadError: Unknown operation type (4)

**Comment by cyxx** [comment]
Hi,

OpType 4 corresponds to SOURCE_COPY. Is up.zip an incremental upgrade package ?

**Comment by dg28gadhavi** [comment]
Yes it was incremental OTA

**Comment by cyxx** [comment]
Thanks for the confirmation. There is not much we can do then, as the image is reconstructed from the flash contents.
