### ISSUE TITLE
Payload dump failed

### ISSUE THREAD

**Issue by weijen6** [cyxx/extract_android_ota_payload#14]
https://ota-oversea-1256119282.file.myqcloud.com/SKW-H0_EEA/2019-09-19_2_skywalker_mp_os_ota4_20190904-2019-07-04_skywalker_mp_os_ota3_20190618_OTA3_EEA.20190920_154535.zip

**Comment by cyxx** [comment]
This looks like an incremental firmware image.

```
Failed: Unhandled operation type (10) - BROTLI_BSDIFF
Failed: Unhandled operation type (4) - SOURCE_COPY
```

Dumping these would require access to the existing firmware image on the EMMC...
