### ISSUE TITLE
python3 in Example

### ISSUE THREAD

**Issue by badaboombamboo** [cyxx/extract_android_ota_payload#20]
The example specifies
python extract_android_ota_payload.py marlin-ota-opm4.171019.021.d1-fd6998a5.zip / tmp /
But this caused an error.
I called 
python3 extract_android_ota_payload.py marlin-ota-opm4.171019.021.d1-fd6998a5.zip / tmp /
And it worked. Could you correct the description?
In the header of the script too

**Comment by pratiktri** [comment]
This saved me a few hours. Not sure why but `python3` works even though python3 is the default on my Ubuntu.

**Comment by cyxx** [comment]
Done with https://github.com/cyxx/extract_android_ota_payload/commit/6952cd8095573b14cae24198fe923347a13790df
