### ISSUE TITLE
Issues extracting realme erofs images

### ISSUE THREAD

**Issue by pjgowtham** [cyxx/extract_android_ota_payload#23]
I have issues extracting images from realme GT master edition payload.bin. The tool throws errors on erofs images. payload_dumper tool however works fine.

OTA Link : https://download.c.realme.com/flash/Rollbackpack/realme_GT_Master_Edition/RMX3360_11_A_fullota_00011011.zip
System,system_ext,vendor,product,odm are erofs

Extracting 'system.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'system_ext.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'product.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'vbmeta_system.img'
Extracting 'cpucp.img'
Extracting 'featenabler.img'
Extracting 'hyp.img'
Extracting 'multiimgoem.img'
Extracting 'oplus_sec.img'
Extracting 'oplusstanvbk.img'
Extracting 'qweslicstore.img'
Extracting 'splash.img'
Extracting 'uefisecapp.img'
Extracting 'vm-bootsys.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'shrm.img'
Extracting 'boot.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'vendor_boot.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'vendor.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'odm.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'dtbo.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'vbmeta.img'
Extracting 'vbmeta_vendor.img'
Extracting 'xbl.img'
Extracting 'xbl_config.img'
Extracting 'aop.img'
Extracting 'tz.img'
Extracting 'modem.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'bluetooth.img'
Extracting 'abl.img'
Extracting 'dsp.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'keymaster.img'
Extracting 'devcfg.img'
Extracting 'qupfw.img'
Extracting 'imagefv.img'
Extracting 'my_product.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'my_engineering.img'
Extracting 'my_stock.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'my_carrier.img'
Extracting 'my_region.img'
Failed: Unhandled operation type (6 - ZERO)
Extracting 'my_heytap.img'

**Comment by cyxx** [comment]
Can you have a try with https://github.com/cyxx/extract_android_ota_payload/commit/df6af3bc978b4bf563ba0e7616f93e2ca2ec6308?

**Comment by pjgowtham** [comment]
Thanks, this worked for me.
